name: paynow

description: Paynow Client helper package to help initiate payments.
version: 4.0.1

email: iamsupercode@outlook.com
homepage: https://github.com/ignertic/paynow

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  http: ^1.2.1
  pretty_dio_logger: 
  crypto: ^3.0.1
  intl: ^0.19.0
  localregex: '>=4.0.5'



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: